# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first (for better cacheing)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3000 (the port our Node server runs on)
EXPOSE 3000

# Start the Node.js application
CMD ["node", "src/app.js"]