services:
  server_app:
    build: 
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/app/data
    # Pass the port argument to the C++ main function at runtime
    command: ["./build/RecommenderApp", "8080"]
    stdin_open: true
    tty: true
  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    ports:
      # Map host port 3000 to container port 5000
      - "5000:3000"
    depends_on:
      - server_app
    environment:
      # This environment variable tells Node where the C++ server is
      - TCP_HOST=server_app
      - TCP_PORT=8080
    stdin_open: true
    tty: true
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.server
    command: ["./build/runTests"]
    profiles:
      - testing
    volumes:
      - ./data:/app/data
  # client_app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.client
  #   # Pass the server name (as IP) and port to the Python script at runtime
  #   command: ["python", "SocketClient.py", "server_app", "8080"]
  #   depends_on:
  #     - server_app
  #   stdin_open: true
  #   tty: true