import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8f9fa' },
    scrollContent: { padding: 20 },
    centerState: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    pageTitle: { fontSize: 24, fontWeight: 'bold', color: '#2c3e50', borderBottomWidth: 2, borderBottomColor: '#007bff', paddingBottom: 10, marginBottom: 20, textAlign: 'right' },
    emptyBox: { backgroundColor: 'white', padding: 40, borderRadius: 12, alignItems: 'center', elevation: 2 },
    emptyText: { color: '#7f8c8d', fontSize: 18, marginBottom: 20 },
    actionBtn: { backgroundColor: '#007bff', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8 },
    actionBtnText: { color: 'white', fontWeight: 'bold' },
    orderCard: { backgroundColor: 'white', borderRadius: 12, padding: 20, elevation: 2, marginBottom: 15 },
    restaurantName: { fontSize: 18, fontWeight: 'bold', color: '#333', textAlign: 'right' },
    orderMeta: { color: '#888', fontSize: 14, marginVertical: 3, textAlign: 'right' },
    orderTotal: { fontWeight: 'bold', fontSize: 18, color: '#007bff', textAlign: 'right', marginBottom: 15 },
    buttonsRow: { flexDirection: 'row-reverse', gap: 10 },
    viewBtn: { flex: 1, backgroundColor: '#e9ecef', padding: 10, borderRadius: 8, alignItems: 'center' },
    viewBtnText: { color: '#007bff', fontWeight: 'bold' },
    deleteBtn: { flex: 1, backgroundColor: '#ffeeba', padding: 10, borderRadius: 8, alignItems: 'center' },
    deleteBtnText: { color: '#dc3545', fontWeight: 'bold' },
    
    card: { backgroundColor: 'white', borderRadius: 16, overflow: 'hidden', elevation: 3 },
    header: { backgroundColor: '#007bff', padding: 20, alignItems: 'center' },
    headerTitle: { color: 'white', fontSize: 24, fontWeight: 'bold' },
    headerSub: { color: 'white', fontSize: 16, marginTop: 5 },
    body: { padding: 20 },
    sectionTitle: { color: '#7f8c8d', fontSize: 16, borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 10, marginBottom: 15, textAlign: 'right' },
    itemsList: { marginBottom: 20 },
    itemRow: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#f1f2f6' },
    itemName: { fontSize: 16, fontWeight: 'bold', textAlign: 'right' },
    itemDesc: { color: '#95a5a6', fontSize: 12, textAlign: 'right', marginTop: 3 },
    itemPrice: { fontWeight: 'bold', fontSize: 18 },
    totalBox: { backgroundColor: '#f1f8ff', padding: 20, borderRadius: 12, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#cce5ff' },
    totalLabel: { fontSize: 18, fontWeight: 'bold', color: '#004085' },
    totalPrice: { fontSize: 24, fontWeight: 'bold', color: '#007bff' },
    actionsRowDetails: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 20, gap: 10 },
    btnOutlinePrimary: { flex: 1, borderWidth: 1, borderColor: '#007bff', padding: 12, borderRadius: 8, alignItems: 'center' },
    btnOutlinePrimaryText: { color: '#007bff', fontWeight: 'bold' },
    btnOutlineWarning: { flex: 1, borderWidth: 1, borderColor: '#f39c12', padding: 12, borderRadius: 8, alignItems: 'center' },
    btnOutlineWarningText: { color: '#f39c12', fontWeight: 'bold' },
    btnOutlineDanger: { flex: 1, borderWidth: 1, borderColor: '#dc3545', padding: 12, borderRadius: 8, alignItems: 'center' },
    btnOutlineDangerText: { color: '#dc3545', fontWeight: 'bold' }
});